version: '3.8'

services:
  web:
    image: backend_python:new-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/austinpartnershipbackend.site:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - web

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root@austinpassword123
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
