version: '3.8'

services:
  web:
    image: your_image_name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql_data:
