version: '3.8'

services:
  web:
    image: your_image_name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root@austinpassword123
      MYSQL_DATABASE: ${DB_NAME}       # Use environment variables for database
      MYSQL_USER: ${DB_USER}           # Use environment variables for user
      MYSQL_PASSWORD: ${DB_PASSWORD}   # Use environment variables for user password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
