services:
  web:
    image: backend_python:new-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env

  apache:
    build:
      context: ./apache
    ports:
      - "443:443"
    volumes:
      - ./apache/htdocs:/usr/local/apache2/htdocs
      - ./apache/certs:/etc/letsencrypt

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root@austinpassword123
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
