name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS via SSH
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'bash -s' < deploy.sh
