name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        key_format: base64
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
          docker stop fastapi_container || true
          docker rm fastapi_container || true
          docker run -d --name fastapi_container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
