name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa

    - name: Test SSH connection
      run: ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no root@93.127.185.162 "echo SSH connection successful"

    - name: Deploy with SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: your_server_ip
        username: root
        key: /tmp/id_rsa
        script: |
          docker pull vasanrock
          docker stop fastapi_container || true
          docker rm fastapi_container || true
          docker run -d --name fastapi_container -p 80:80 vasanrock
